name: yueyisui's blog
author: yueyisui
url: https://yueyisui.github.io
baseurl: https://yueyisui.github.io
resume_site: 
description: 
github_username: yueyisui
github: github.com/yueyisui
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : https://yueyisui.github.io
    owner : 
    admin : 
